version: '3.7'

services:
  teamspeak:
    image: teamspeak
    restart: unless-stopped
    environment:
      - TS3SERVER_LICENSE=accept
    ports:
      - '9987:9987/udp'
      - '30033:30033'
#      - '10011:10011'
    volumes:
      - ./data:/var/ts3server/

