version: '3.7'

services:
  traefik:
    image: traefik:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entryPoints=web-secure
      - traefik.http.routers.whoami.rule=Host(`whoami.crstian.me`)
      - traefik.http.routers.whoami.tls.certresolver=default


     
